/*
Hashing is a technique used to store the number with their frequency in a easy manner.
Here, we are using unordered_map to store the frequency of each number in the array.

Question: Given an array of size "n" wea are also given "Q" queries for each of the query we have to tell the frequency of that number in the array.




#include <iostream>
#include <unordered_map>
#include <vector>

int main() {
    int n,Q;
    std::cin>>n>>Q;
    std::vector<int> arr(n);

    std::unordered_map<int,int> freq;
for(auto &x : arr) {
    std::cin>>x;
    freq[arr[x]] = freq[arr[x]] + 1;
}
for(int i = 0; i < Q; i++) {
    int queries; 
    std::cin>>queries;
    int count = freq[i];
    std::cout<<count<<"\n";
}
return 0;


}

*/



/*
Question: given an array of number we have to find and print anu number with maximum frequency and minimum frequency.






#include <bits/stdc++.h>
using namespace std;

int main() {
    int n;
    cin>>n;
    vector<int> arr (n);
    unordered_map<int,int> freq;
    for(auto &x : arr) {
        cin>>x;
        freq[x] = freq[x] + 1;
    }
    int max_freq = INT_MIN;
    int min_freq = INT_MAX;
    int max_num, min_num;
    for(auto it : freq) {
        if(it.second > max_freq) {
            max_freq = it.second;
            max_num = it.first;
        }
        if(it.second < min_freq) {
            min_freq = it.second;
            min_num = it.first;
        }
    }
    cout<<"Maximum frequency number is: "<<max_num<<" with frequency: "<<max_freq<<"\n";
    cout<<"Minimum frequency number is: "<<min_num<<" with frequency: "<<min_freq<<"\n";
    return 0;
}
    */


/*
Find the number of subarrays with sum == k    
    
    


#include <bits/stdc++.h>
using namespace std;

int main() {
    int n, k;
    cin>>n>>k;
    vector<int> arr(n);
    for(auto &x : arr) {
        cin>>x;
    }
    unordered_map<int,int> freq;
    int sum = 0;
    int count = 0;
    for(int i = 0; i < n; i++) {
        sum += arr[i];
        if(sum == k) {
            count++;
        }
        if(freq.find(sum - k) != freq.end()) {
            count += freq[sum - k];
        }
        freq[sum]++;
    }
    cout<<count<<"\n";
    return 0;
}
    */


/*
B. ABAB Construction
time limit per test
1 second
memory limit per test
256 megabytes

There is a string T
of length n, such that Ti= 'a' for all odd i and Ti= 'b' for all even i

.

One day, Bob generated a string S

with the following algorithm.

    Initialize S

to the empty string.
Remove either the first letter or the last letter from T
, and append it to S
.
If T
is empty, terminate and return the string S

    . Otherwise, go back to the second step. 

Then, Bob wrote down the generated string S

on a note and forgot about it for a few years. The note was worn out when Bob found it, and someone might have secretly changed some letters. Of course, Bob wants to know if someone did alter the string!

You are given a string X
of length n

, which consists of 'a', 'b', and '?'.

Please determine if there exists a string A

which satisfies the following conditions:

    |A|=n

;
Ai
is either 'a' or 'b' for all 1≤i≤n
;
Ai=Xi
for all 1≤i≤n such that Xi
is not '?';
The string A

    can be generated from the algorithm described above. 

Input

Each test contains multiple test cases. The first line contains the number of test cases t
(1≤t≤104

). The description of the test cases follows.

The first line of each test case contains a single integer n
(1≤n≤200000

).

The second line of each test case contains a string X
of length n

, consisting of 'a', 'b', and '?'.

It is guaranteed that the sum of n
over all test cases does not exceed 200000

.
Output

If there is a string A

that satisfies all conditions, output "YES" on a separate line.

If there is no string A

that satisfies all conditions, output "NO" on a separate line.

You can output the answer in any case. For example, the strings "yEs", "yes", "Yes" will also be recognized as positive responses.
Example
Input
Copy

4
5
ababa
5
baaba
5
?b?ab
6
aa?b?b

Output
Copy

YES
NO
YES
NO

Note

For the second test case, the string "baaba" cannot be generated by the algorithm described above.

For the third test case, the string "abaab" can be generated by the algorithm described above:

    Initially, T

is "ababa" and S
is empty.
Remove the first letter from T
. T becomes "baba" and S
becomes "a".
Remove the first letter from T
. T becomes "aba" and S
becomes "ab".
Remove the last letter from T
. T becomes "ab" and S
becomes "aba".
Remove the first letter from T
. T becomes "b" and S
becomes "abaa".
Remove the last letter from T
. T becomes empty and S becomes "abaab". 



#include<bits/stdc++.h>
using namespace std;
int main(){
    int t;scanf("%d",&t);
    while(t--){
        int n;scanf("%d",&n);
        string X;cin>>X;
        // State: parity of l (l starts at 1, parity=1 means odd)
        // At step k, l+r=n+1-k
        // Take front: T[l]='a' if l_par==1 else 'b', new l_par flips
        // Take back: T[r]='a' if r_par==1 else 'b', l_par unchanged
        // r_par = parity(n+1-k) XOR l_par (since l+r=n+1-k, parity(r)=parity(n+1-k)^parity(l))
        // We track which parities of l are reachable
        // dp[p] = is parity p of l reachable?
        bool dp[2]={false,false};
        dp[1]=true; // l=1, parity=1 (odd)
        bool ok=false;
        for(int k=0;k<n;k++){
            bool ndp[2]={false,false};
            int sum_par=(n+1-k)%2; // parity of l+r at step k
            char c=X[k];
            for(int p=0;p<2;p++){
                if(!dp[p])continue;
                // option front: char='a' if p==1 else 'b'
                char cf=(p==1)?'a':'b';
                if(c=='?'||c==cf){
                    ndp[p^1]=true;
                }
                // option back: r_par = sum_par ^ p
                int rp=sum_par^p;
                char cb=(rp==1)?'a':'b';
                if(c=='?'||c==cb){
                    ndp[p]=true;
                }
            }
            dp[0]=ndp[0];dp[1]=ndp[1];
        }
        if(dp[0]||dp[1])printf("YES\n");
        else printf("NO\n");
    }
}
*/

#include<bits/stdc++.h>
using namespace std;
int main(){
    int t;scanf("%d",&t);
    while(t--){
        int n,k;scanf("%d%d",&n,&k);
        if(k<n||k>2*n-1){puts("NO");continue;}
        puts("YES");
        int m=k-n+1;
        for(int i=1;i<=m;i++)printf("%d ",i);
        for(int i=1;i<=m;i++)printf("%d ",i);
        for(int i=m+1;i<=n;i++)printf("%d %d ",i,i);
        printf("\n");
    }
}